services:
  nestapp:
    build:
      context: ./balancecore
      dockerfile: Dockerfile
    command: sh /home/node/app/entrypoint/entrypoint.sh
    depends_on:
      - postgres
      - kafka
    ports:
      - 3003:3000
    volumes:
      - ./balancecore:/home/node/app
      - /home/node/app/node_modules
    environment:
      TZ: Atlantic/Cape_Verde
    networks:
      - balance-network
  goapp:
    build:
      context: ./walletcore
      dockerfile: Dockerfile
    # command: sh /app/entrypoint/entrypoint.sh
    depends_on:
      - mysql
    environment:
      TZ: Atlantic/Cape_Verde
    ports:
      - 8080:8080
    volumes:
      - ./walletcore:/app/src
    networks:
      - wallet-network

  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      TZ: Atlantic/Cape_Verde
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - wallet-network
  kafka:
    image: "confluentinc/cp-enterprise-kafka:6.1.0"
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      TZ: Atlantic/Cape_Verde
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      CONFLUENT_METRICS_ENABLE: "false"
    networks:
      - wallet-network
      - balance-network

  control-center:
    image: confluentinc/cp-enterprise-control-center:6.1.0
    hostname: control-center
    container_name: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka:29092"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
    networks:
      - wallet-network

  mysql:
    image: mysql:9.5.0
    # platform: linux/amd64
    container_name: mysql-wallet
    tty: true
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      # MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - wallet-network

  postgres:
    image: postgres:15
    container_name: postgres-balance
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - balance-network

volumes:
  mysql-data:
  postgres-data:

networks:
  wallet-network:
    driver: bridge
  balance-network:
    driver: bridge
